APP-MOBILE: listado de certificados
andes/mobile-app pull request #116
Opened 2020-08-28 13:59 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-49
https://proyectos.andes.gob.ar/browse/AM-51

### Funcionalidad desarrollada 
1. Se agrega la opción de Mi Historia de Salud a la pantalla principal
2. Podes acceder a las distintas categorías, y descarga los adjuntos relacionados a los registros si corresponde.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

https://gist.github.com/juuliotero/317fffa6ae571d8ac6cfa4b40d9ce10b
https://gist.github.com/juuliotero/a7d6dc8ee10d1c9b49cfd25a953f8604

### Requiere actualizaciones en la API
- [X] Si https://github.com/andes/api/pull/1063
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-09-08 17:15 UTC, kroce requested changes
En el dispositivo donde realicé la prueba, la opción se sale de los límites

![icono](https://user-images.githubusercontent.com/18030170/92507669-b2ea7e00-f1dd-11ea-917c-7234dba22472.png)

2020-09-09 16:31 UTC, kroce approved these changes

2020-09-18 01:59 UTC, sychus approved these changes
Avanzar con la publicación. Pero la verdad que deberíamos hacer un buen refactor de código para emprolijar.
Anotar en backlog

2020-09-18 01:59 UTC, sychus commented on src/providers/paciente.ts
> +        });
async await y callback (usar solo async await) para la prox. boy scouting

2020-09-18 02:21 UTC, liquid36 commented on src/providers/paciente.ts
> +        });
Deberían deprecar el servicio _NetworkProvider_, mi primera y peor decisión en Andes. jajaja
Transformar observable a promesas no tenía sentido ni futuro. RxJS estalló en popularidad en Angular.

2020-09-18 16:55 UTC, merged