MPI: arreglo al escanear un DNI como profesional
andes/mobile-app pull request #129
Opened 2021-02-10 16:45 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-119

### Funcionalidad desarrollada 
1. Se actualizan las rutas de paciente
2. Se arreglan errores al guardar pacientes escaneados

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-10 17:40 UTC, negro89 requested changes

2021-02-10 17:40 UTC, negro89 commented on src/app/pages/profesional/mpi/registro-paciente/registro-paciente.ts
> +        this.mpiService.get({ search: datos.documento.toString() }).then((resultado: any[]) => {
El nuevo get de paciente discrimina el tipo de búsqueda por el parámetro 'search' (Si está realiza multimatch y sino simplequery) a diferencia del anterior que el tipo iba explícito en 'type'. Acá deberíamos mantener la búsqueda simpĺequery enviando los params como antes pero sin el type y ademas del documento incluir:

- sexo, ya que en teoría el documento podría repetirse
- activo: true, para no traer pacientes vinculados

2021-02-10 17:40 UTC, negro89 commented on src/app/pages/profesional/mpi/registro-paciente/registro-paciente.ts
>                  this.mpiService.getById(this.paciente.id).then((pacUpdate: any) => {
Si bien esta consulta ya estaba y no era el objetivo de la tarea, a modo de mejora pienso que si tanto el get (Como búsqueda simplequery) como el getById traen un paciente completo de la misma colección quizás no sea necesario hacer dos request a la api por el mismo paciente (Verificar). Además de esta manera, en caso de que el paciente sea nuevo, se podrían setear una sola vez sus datos.

2021-02-11 12:17 UTC, juuliotero commented on src/app/pages/profesional/mpi/registro-paciente/registro-paciente.ts
>                  this.mpiService.getById(this.paciente.id).then((pacUpdate: any) => {
Corregido!

2021-02-11 12:17 UTC, juuliotero commented on src/app/pages/profesional/mpi/registro-paciente/registro-paciente.ts
> +        this.mpiService.get({ search: datos.documento.toString() }).then((resultado: any[]) => {
Corregido!

2021-02-11 13:39 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3296](http://condorpiedra.andes.gob.ar:85/3296/mochawesome.html)
CYPRESS RUN: [2411](https://dashboard.cypress.io/projects/xr7gft/runs/2411/specs)
TEST START: 2021-02-11T13:28:58.202Z
TOTAL: 358
SUCCESS: 356
FAIL: 1
SKIPPED: 1

2021-02-11 14:08 UTC, kroce approved these changes

2021-02-11 14:14 UTC, negro89 approved these changes

2021-02-11 14:31 UTC, merged