Descarga de certificados nativa
andes/mobile-app pull request #130
Opened 2021-02-10 18:17 UTC by andrrrl

- chore(downloader): plugin de descargas nativas
- feat(version): se actualiza versión
- feat(sdk): soporte para APIs 19 a 30
- feat(certificados): descarga nativa
- feat(version): v4.1.2

### Requerimiento
 

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-02-11 16:57 UTC, andrrrl commented
(No miren los commits, quedaron un espanto jaja)

2021-02-11 17:22 UTC, martinebucarey requested changes

2021-02-11 17:22 UTC, martinebucarey commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +                console.log(elementoAdjuntos);
por acá se paso un console.log

2021-02-11 17:22 UTC, martinebucarey commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +                    fileTransfer.download(uri, localFile)
acá se podría usar async/await??, download devuelve una Promise

2021-02-11 17:23 UTC, martinebucarey commented
> (No miren los commits, quedaron un espanto jaja)

[https://github.com/andes/andes/wiki/2---Gu%C3%ADa-para-GIT#gu%C3%ADa-de-estilos-para-el-mensaje-del-commit](url) chiste bothoo

2021-02-18 18:23 UTC, andrrrl commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +                    fileTransfer.download(uri, localFile)
Ese fileTransfer.download es de un paquete de ionic-native, gestiona descargas de manera nativa del OS del dispositivo.

2021-02-18 18:24 UTC, andrrrl commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +                console.log(elementoAdjuntos);
ya se quitó! gracias!

2021-02-19 14:56 UTC, martinebucarey approved these changes

2021-02-19 19:02 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3391](http://condorpiedra.andes.gob.ar:85/3391/mochawesome.html)
CYPRESS RUN: [2494](https://dashboard.cypress.io/projects/xr7gft/runs/2494/specs)
TEST START: 2021-02-19T19:00:36.316Z
TOTAL: 300
SUCCESS: 289
FAIL: 10
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-22 16:27 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3401](http://condorpiedra.andes.gob.ar:85/3401/mochawesome.html)
CYPRESS RUN: [2504](https://dashboard.cypress.io/projects/xr7gft/runs/2504/specs)
TEST START: 2021-02-22T16:26:02.169Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-22 16:58 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3405](http://condorpiedra.andes.gob.ar:85/3405/mochawesome.html)
CYPRESS RUN: [2507](https://dashboard.cypress.io/projects/xr7gft/runs/2507/specs)
TEST START: 2021-02-22T16:56:49.819Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-22 17:05 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3406](http://condorpiedra.andes.gob.ar:85/3406/mochawesome.html)
CYPRESS RUN: [2508](https://dashboard.cypress.io/projects/xr7gft/runs/2508/specs)
TEST START: 2021-02-22T17:04:37.165Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-22 17:16 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3407](http://condorpiedra.andes.gob.ar:85/3407/mochawesome.html)
CYPRESS RUN: [2509](https://dashboard.cypress.io/projects/xr7gft/runs/2509/specs)
TEST START: 2021-02-22T17:15:36.753Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-22 18:02 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3409](http://condorpiedra.andes.gob.ar:85/3409/mochawesome.html)
CYPRESS RUN: [2511](https://dashboard.cypress.io/projects/xr7gft/runs/2511/specs)
TEST START: 2021-02-22T18:00:44.728Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-23 12:32 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3418](http://condorpiedra.andes.gob.ar:85/3418/mochawesome.html)
CYPRESS RUN: [2515](https://dashboard.cypress.io/projects/xr7gft/runs/2515/specs)
TEST START: 2021-02-23T12:30:39.977Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-23 18:39 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [3429](http://condorpiedra.andes.gob.ar:85/3429/mochawesome.html)
CYPRESS RUN: [2525](https://dashboard.cypress.io/projects/xr7gft/runs/2525/specs)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-23 18:49 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [3430](http://condorpiedra.andes.gob.ar:85/3430/mochawesome.html)
CYPRESS RUN: [2525](https://dashboard.cypress.io/projects/xr7gft/runs/2525/specs)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-23 18:54 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [3431](http://condorpiedra.andes.gob.ar:85/3431/mochawesome.html)
CYPRESS RUN: [2526](https://dashboard.cypress.io/projects/xr7gft/runs/2526/specs)
TEST START: 2021-02-23T18:52:47.007Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-24 15:38 UTC, closed without merging

2021-02-24 15:38 UTC, andrrrl commented
*No borrar la rama*

2021-06-01 18:11 UTC, andrrrl commented
kejente