AM: permitir al profesional cambiar de organización
andes/mobile-app pull request #136
Opened 2021-02-19 15:31 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-95

### Funcionalidad desarrollada 
1. Suma opción al menú para permitir al profesional cambiar de organización
2. Limpieza de código

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-24 16:11 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3436](http://condorpiedra.andes.gob.ar:85/3436/mochawesome.html)
CYPRESS RUN: [2531](https://dashboard.cypress.io/projects/xr7gft/runs/2531/specs)
TEST START: 2021-02-24T16:09:57.584Z
TOTAL: 354
SUCCESS: 352
FAIL: 1
SKIPPED: 1

2021-02-24 18:03 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3443](http://condorpiedra.andes.gob.ar:85/3443/mochawesome.html)
CYPRESS RUN: [2538](https://dashboard.cypress.io/projects/xr7gft/runs/2538/specs)
TEST START: 2021-02-24T18:02:18.962Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-26 12:56 UTC, waltergarrido approved these changes

2021-03-11 17:56 UTC, palita1991 requested changes
Al ingresar como profesional en el castro, en "mis agendas" tambien me sale una agenda del efector de centenario. Ahora que te deja cambiar de efector estaría bueno que solo se vean las agendas correspondientes al efector
![image](https://user-images.githubusercontent.com/30004190/110832335-f2bc1c00-8279-11eb-9d4e-fd7ade183ba8.png)

2021-03-16 14:38 UTC, andrrrl commented
> Al ingresar como profesional en el castro, en "mis agendas" tambien me sale una agenda del efector de centenario. Ahora que te deja cambiar de efector estaría bueno que solo se vean las agendas correspondientes al efector
> ![image](https://user-images.githubusercontent.com/30004190/110832335-f2bc1c00-8279-11eb-9d4e-fd7ade183ba8.png)

Está bueno lo que decís @palita1991, creo que se soluciona con un filtro por efector, por defecto seleccionado el actual.

2021-03-16 15:04 UTC, andrrrl reviewed
No chequea permisos de RUP, es decir si el profesional no tiene permiso para registrar en RUP no debería mostrar la opción de adjuntar a RUP. Lo dejo como comentario por si lo querés validar con alguien.

2021-03-25 16:06 UTC, juuliotero commented
> No chequea permisos de RUP, es decir si el profesional no tiene permiso para registrar en RUP no debería mostrar la opción de adjuntar a RUP. Lo dejo como comentario por si lo querés validar con alguien.

Se agrega control de permiso de rup en home

2021-03-29 18:28 UTC, palita1991 approved these changes

2021-04-14 11:12 UTC, andrrrl approved these changes
:green_circle:

2021-04-14 12:08 UTC, merged