AM: permitir ver laboratorios de familiar
andes/mobile-app pull request #137
Opened 2021-02-19 19:39 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-52

### Funcionalidad desarrollada 

1. Habilita la consulta de laboratorios para familiares

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1281
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-24 16:00 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3435](http://condorpiedra.andes.gob.ar:85/3435/mochawesome.html)
CYPRESS RUN: [2530](https://dashboard.cypress.io/projects/xr7gft/runs/2530/specs)
TEST START: 2021-02-24T15:59:30.631Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-25 11:31 UTC, liquid36 approved these changes

2021-03-18 12:51 UTC, andrrrl requested changes
- Agregué al paciente "BOTTA MARIANO" de 6 años como hijo en servidor _demo_
- Fui a ver sus laboratorios la lista se ve.
- Pero si quiero abrir/descargar alguno tira error (ver captura).
![image](https://user-images.githubusercontent.com/11394455/111628641-35787980-87cf-11eb-9031-c0acb38553c4.png)

2021-03-18 14:19 UTC, andrrrl commented on src/app/pages/laboratorios/laboratorios.page.html
> +<ion-content class="dark" [class.familiar]="familiar">
Me parece que es un problema heredado, pero me doy cuenta que no figura el nombre del laboratorio (term), se puede usar ya que está en el objeto:
`{ "paciente": "...", "prestacion": { "snomed": { "conceptId": "4241000179101", "term": "informe de laboratorio", ... },`
No sé si está siempre presente, se puede mostrar si existe. Avisame si necesitás una mano con ese dato, lo pondría en el título junto con la fecha, onda: {{ fecha }} - {{ term }}

2021-03-18 18:07 UTC, juuliotero commented
> * Agregué al paciente "BOTTA MARIANO" de 6 años como hijo en servidor _demo_
> * Fui a ver sus laboratorios la lista se ve.
> * Pero si quiero abrir/descargar alguno tira error (ver captura).
>   ![image](https://user-images.githubusercontent.com/11394455/111628641-35787980-87cf-11eb-9031-c0acb38553c4.png)

corregido desde la api

2021-03-18 21:17 UTC, andrrrl requested changes

2021-03-18 21:17 UTC, andrrrl commented on src/app/pages/laboratorios/laboratorios.page.html
> +                      name="ios-cloud-download-outline"></ion-icon>
Me di cuenta que los íconos no se ven
```suggestion
                      name="cloud-download-outline"></ion-icon>
```

2021-03-18 21:17 UTC, andrrrl commented on src/app/pages/laboratorios/laboratorios.page.html
> +                      name="md-alert">
```suggestion
                      name="alert-circle-outline">
```

2021-03-18 21:18 UTC, andrrrl commented
> > * Agregué al paciente "BOTTA MARIANO" de 6 años como hijo en servidor _demo_
> > * Fui a ver sus laboratorios la lista se ve.
> > * Pero si quiero abrir/descargar alguno tira error (ver captura). 
> corregido desde la api
Anduvo joya!

2021-03-25 13:38 UTC, juuliotero commented on src/app/pages/laboratorios/laboratorios.page.html
> +                      name="ios-cloud-download-outline"></ion-icon>
listo

2021-03-25 13:38 UTC, juuliotero commented on src/app/pages/laboratorios/laboratorios.page.html
> +                      name="md-alert">
listo

2021-04-14 14:00 UTC, kroce approved these changes

2021-04-14 14:01 UTC, merged