AM: diferenciar entre login y activación de cuenta
andes/mobile-app pull request #151
Opened 2021-05-12 14:56 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-151

### Funcionalidad desarrollada 
1. Se suma un botón de 'Ingresar código de activación' que cambie los labels del formulario del login 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-12 17:19 UTC, martinebucarey requested changes

2021-05-12 17:19 UTC, martinebucarey commented on src/app/pages/login/login.page.html
> +                <h2 class="welcome-title" *ngIf="!authService.user && activacion">Activar cuenta</h2>
```suggestion
                <h2 class="welcome-title" *ngIf="!authService.user">{{ activacion ? Activar cuenta : Ingreso}}</h2>
```

2021-05-12 18:21 UTC, juuliotero commented on src/app/pages/login/login.page.html
> +                <h2 class="welcome-title" *ngIf="!authService.user && activacion">Activar cuenta</h2>
corregido

2021-05-12 18:23 UTC, martinebucarey approved these changes

2021-05-13 13:46 UTC, palita1991 approved these changes

2021-05-17 16:21 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4081](http://condorpiedra.andes.gob.ar:85/4081/mochawesome.html)
CYPRESS RUN: [3117](https://dashboard.cypress.io/projects/xr7gft/runs/3117/specs)
TEST START: 2021-05-17T16:21:09.088Z
TOTAL: 388
SUCCESS: 388
FAIL: 0
SKIPPED: 0

2021-05-17 16:40 UTC, kroce approved these changes

2021-05-17 16:59 UTC, andrrrl approved these changes
:100:

2021-05-17 18:39 UTC, merged