AM: registro de hijos menores a 11 años
andes/mobile-app pull request #152
Opened 2021-05-13 18:50 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-153

### Funcionalidad desarrollada 
1. Permitir al usuario registrar hijos menores a 11 años desde la aplicación

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1386
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-13 19:02 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [4060](http://condorpiedra.andes.gob.ar:85/4060/mochawesome.html)
CYPRESS RUN: [3096](https://dashboard.cypress.io/projects/xr7gft/runs/3096/specs)
TEST START: 2021-05-13T19:02:36.725Z
TOTAL: 388
SUCCESS: 388
FAIL: 0
SKIPPED: 0

2021-05-17 18:58 UTC, andrrrl commented
Agrego un familiar y me aparece sin el ícono a la derecha. Lo demás todo bien hasta acá!
![image](https://user-images.githubusercontent.com/11394455/118541895-a59c7080-b728-11eb-9346-2564713d94bf.png)

2021-05-18 16:40 UTC, andrrrl requested changes

2021-05-18 16:40 UTC, andrrrl commented on src/app/pages/mis-familiares/mis-familiares.page.ts
> -export class MisFamiliaresPage implements OnInit {
Te faltó sacar OnInit de los imports :sweat_smile:

2021-05-18 16:49 UTC, andrrrl commented
> > Agrego un familiar y me aparece sin el ícono a la derecha. Lo demás todo bien hasta acá!
> > ![image](https://user-images.githubusercontent.com/11394455/118541895-a59c7080-b728-11eb-9346-2564713d94bf.png)
> 
> que raro...a mi me apareció de toque

@kroce es porque comprueba edad < 11, si pero en api comprueba edad > 11. Te deja ingresar un hije de 11, pero después no te muestra la flechita

2021-05-18 17:12 UTC, juuliotero commented on src/app/pages/mis-familiares/mis-familiares.page.ts
> -export class MisFamiliaresPage implements OnInit {
corregido

2021-05-27 13:40 UTC, andrrrl approved these changes

2021-05-27 16:45 UTC, merged