feat(certificados): Implementa descarga de prestación o registro
andes/mobile-app pull request #156
Opened 2021-06-01 17:06 UTC by kroce

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-155

### Funcionalidad desarrollada 

1. Se agregó metodo que descarga la prestación pegandole a la ruta de descargas
2. Usa plugin de transferencia y apertura de archivos nativa, compatible con Android y iOS

### UserStory llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/AM-155
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1416
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-06-01 18:27 UTC, andrrrl commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +                    // this.loadingController.dismiss();
código comentado detected

2021-06-01 18:31 UTC, andrrrl requested changes
Sólo esa cosita del mime-type, no me odies!

2021-06-01 18:31 UTC, andrrrl commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +                new FileOpener().showOpenWithDialog(entry.toURL(), '')
Pasando el mime-type hay más chance de que lo abra la app apropiada según el tipo de archivo.
```suggestion
                new FileOpener().showOpenWithDialog(entry.toURL(), 'application/pdf')
```

2021-06-01 18:31 UTC, andrrrl commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +import { FileTransfer, FileTransferObject } from '../../../../../node_modules/@ionic-native/file-transfer/ngx';
Lindo hack :stuck_out_tongue_closed_eyes:

2021-06-01 18:41 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4235](http://condorpiedra.andes.gob.ar:85/4235/mochawesome.html)
CYPRESS RUN: [3261](https://dashboard.cypress.io/projects/xr7gft/runs/3261/specs)
TEST START: 2021-06-01T18:41:13.977Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-06-01 18:50 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4236](http://condorpiedra.andes.gob.ar:85/4236/mochawesome.html)
CYPRESS RUN: [3262](https://dashboard.cypress.io/projects/xr7gft/runs/3262/specs)
TEST START: 2021-06-01T18:49:57.607Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-02 15:53 UTC, liquid36 commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +            const localFile = `${File.dataDirectory}certificado.pdf`;
No siempre estamos hablando de un certificado.

2021-06-02 15:54 UTC, liquid36 commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +            this.abrirAdjunto(registro);
Abrir adjunto difiere de dercargarPrestación. Debeŕia manejar todo la misma lógica de descarga archivos.

2021-06-02 15:56 UTC, liquid36 reviewed
El buscar por prestaciones se implemento al final?

2021-06-04 16:23 UTC, kroce commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +            const localFile = `${File.dataDirectory}certificado.pdf`;
solved

2021-06-04 16:23 UTC, kroce commented on src/app/pages/historia-salud/categorias/detalle-categoria.ts
> +            this.abrirAdjunto(registro);
done

2021-06-04 16:24 UTC, kroce commented
> El buscar por prestaciones se implemento al final?

Se implementó. Estoy por ver el tema cdas

2021-06-04 18:18 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4256](http://condorpiedra.andes.gob.ar:85/4256/mochawesome.html)
CYPRESS RUN: [3282](https://dashboard.cypress.io/projects/xr7gft/runs/3282/specs)
TEST START: 2021-06-04T18:17:49.218Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-06-04 18:29 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4257](http://condorpiedra.andes.gob.ar:85/4257/mochawesome.html)
CYPRESS RUN: [3283](https://dashboard.cypress.io/projects/xr7gft/runs/3283/specs)
TEST START: 2021-06-04T18:29:18.920Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-04 18:51 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4258](http://condorpiedra.andes.gob.ar:85/4258/mochawesome.html)
CYPRESS RUN: [3284](https://dashboard.cypress.io/projects/xr7gft/runs/3284/specs)
TEST START: 2021-06-04T18:51:12.858Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-04 18:55 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4259](http://condorpiedra.andes.gob.ar:85/4259/mochawesome.html)
CYPRESS RUN: [3285](https://dashboard.cypress.io/projects/xr7gft/runs/3285/specs)
TEST START: 2021-06-04T18:54:40.029Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-07 18:15 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4270](http://condorpiedra.andes.gob.ar:85/4270/mochawesome.html)
CYPRESS RUN: [3296](https://dashboard.cypress.io/projects/xr7gft/runs/3296/specs)
TEST START: 2021-06-07T18:15:12.089Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-06-07 18:38 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4272](http://condorpiedra.andes.gob.ar:85/4272/mochawesome.html)
CYPRESS RUN: [3298](https://dashboard.cypress.io/projects/xr7gft/runs/3298/specs)
TEST START: 2021-06-07T18:37:00.270Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 11:52 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4276](http://condorpiedra.andes.gob.ar:85/4276/mochawesome.html)
CYPRESS RUN: [3302](https://dashboard.cypress.io/projects/xr7gft/runs/3302/specs)
TEST START: 2021-06-08T11:51:44.156Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-06-08 14:33 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4277](http://condorpiedra.andes.gob.ar:85/4277/mochawesome.html)
CYPRESS RUN: [3303](https://dashboard.cypress.io/projects/xr7gft/runs/3303/specs)
TEST START: 2021-06-08T14:32:47.114Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 15:51 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4284](http://condorpiedra.andes.gob.ar:85/4284/mochawesome.html)
CYPRESS RUN: [3310](https://dashboard.cypress.io/projects/xr7gft/runs/3310/specs)
TEST START: 2021-06-08T15:51:12.572Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 16:26 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4288](http://condorpiedra.andes.gob.ar:85/4288/mochawesome.html)
CYPRESS RUN: [3314](https://dashboard.cypress.io/projects/xr7gft/runs/3314/specs)
TEST START: 2021-06-08T16:25:38.461Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 16:52 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4290](http://condorpiedra.andes.gob.ar:85/4290/mochawesome.html)
CYPRESS RUN: [3316](https://dashboard.cypress.io/projects/xr7gft/runs/3316/specs)
TEST START: 2021-06-08T16:52:28.345Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 17:11 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4291](http://condorpiedra.andes.gob.ar:85/4291/mochawesome.html)
CYPRESS RUN: [3317](https://dashboard.cypress.io/projects/xr7gft/runs/3317/specs)
TEST START: 2021-06-08T17:11:27.036Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 17:57 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4292](http://condorpiedra.andes.gob.ar:85/4292/mochawesome.html)
CYPRESS RUN: [3318](https://dashboard.cypress.io/projects/xr7gft/runs/3318/specs)
TEST START: 2021-06-08T17:56:43.520Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 18:18 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4294](http://condorpiedra.andes.gob.ar:85/4294/mochawesome.html)
CYPRESS RUN: [3320](https://dashboard.cypress.io/projects/xr7gft/runs/3320/specs)
TEST START: 2021-06-08T18:17:25.315Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 18:47 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4295](http://condorpiedra.andes.gob.ar:85/4295/mochawesome.html)
CYPRESS RUN: [3321](https://dashboard.cypress.io/projects/xr7gft/runs/3321/specs)
TEST START: 2021-06-08T18:46:40.778Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 23:24 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4299](http://condorpiedra.andes.gob.ar:85/4299/mochawesome.html)
CYPRESS RUN: [3325](https://dashboard.cypress.io/projects/xr7gft/runs/3325/specs)
TEST START: 2021-06-08T23:24:23.678Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 23:42 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4303](http://condorpiedra.andes.gob.ar:85/4303/mochawesome.html)
CYPRESS RUN: [3329](https://dashboard.cypress.io/projects/xr7gft/runs/3329/specs)
TEST START: 2021-06-08T23:41:34.445Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 23:45 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4304](http://condorpiedra.andes.gob.ar:85/4304/mochawesome.html)
CYPRESS RUN: [3330](https://dashboard.cypress.io/projects/xr7gft/runs/3330/specs)
TEST START: 2021-06-08T23:44:24.164Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 23:48 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4305](http://condorpiedra.andes.gob.ar:85/4305/mochawesome.html)
CYPRESS RUN: [3331](https://dashboard.cypress.io/projects/xr7gft/runs/3331/specs)
TEST START: 2021-06-08T23:48:15.170Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 23:51 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4306](http://condorpiedra.andes.gob.ar:85/4306/mochawesome.html)
CYPRESS RUN: [3332](https://dashboard.cypress.io/projects/xr7gft/runs/3332/specs)
TEST START: 2021-06-08T23:51:00.240Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 23:54 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4307](http://condorpiedra.andes.gob.ar:85/4307/mochawesome.html)
CYPRESS RUN: [3333](https://dashboard.cypress.io/projects/xr7gft/runs/3333/specs)
TEST START: 2021-06-08T23:53:49.742Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-08 23:58 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4308](http://condorpiedra.andes.gob.ar:85/4308/mochawesome.html)
CYPRESS RUN: [3334](https://dashboard.cypress.io/projects/xr7gft/runs/3334/specs)
TEST START: 2021-06-08T23:57:55.881Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-09 11:17 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4311](http://condorpiedra.andes.gob.ar:85/4311/mochawesome.html)
CYPRESS RUN: [3337](https://dashboard.cypress.io/projects/xr7gft/runs/3337/specs)
TEST START: 2021-06-09T11:16:51.110Z
TOTAL: 2
SUCCESS: 1
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-09 11:20 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4312](http://condorpiedra.andes.gob.ar:85/4312/mochawesome.html)
CYPRESS RUN: [3338](https://dashboard.cypress.io/projects/xr7gft/runs/3338/specs)
TEST START: 2021-06-09T11:19:48.402Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-09 16:06 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4313](http://condorpiedra.andes.gob.ar:85/4313/mochawesome.html)
CYPRESS RUN: [3339](https://dashboard.cypress.io/projects/xr7gft/runs/3339/specs)
TEST START: 2021-06-09T16:05:35.379Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-10 12:09 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4317](http://condorpiedra.andes.gob.ar:85/4317/mochawesome.html)
CYPRESS RUN: [3343](https://dashboard.cypress.io/projects/xr7gft/runs/3343/specs)
TEST START: 2021-06-10T12:08:44.371Z
TOTAL: 395
SUCCESS: 394
FAIL: 0
SKIPPED: 1

2021-06-11 13:46 UTC, andrrrl approved these changes

2021-06-11 13:49 UTC, palita1991 approved these changes

2021-06-11 16:23 UTC, merged