Fixes de visualización Android 7
andes/mobile-app pull request #158
Opened 2021-06-11 13:38 UTC by andrrrl

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/AM-160

### Funcionalidad desarrollada 

1. Se introdujeron cambios en algunas reglas CSS para compatibilidad con devices Android 7
2. Además se mejoró la visualización en pantallas pequeñas

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-06-11 18:54 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [4332](http://condorpiedra.andes.gob.ar:85/4332/mochawesome.html)
CYPRESS RUN: [3355](https://dashboard.cypress.io/projects/xr7gft/runs/3355/specs)
TEST START: 2021-06-11T18:53:48.687Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-11 19:03 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [4333](http://condorpiedra.andes.gob.ar:85/4333/mochawesome.html)
CYPRESS RUN: [3356](https://dashboard.cypress.io/projects/xr7gft/runs/3356/specs)
TEST START: 2021-06-11T19:02:42.770Z
TOTAL: 3
SUCCESS: 2
FAIL: 0
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-17 14:21 UTC, kroce requested changes
Test en el emulador (Android 7.1): Algunas pantallas todavia tienen problemas en la visualización. 
- Farmacias
- Tu mapa de salud
- Mi historial de turnos
- Datos personales
![historial](https://user-images.githubusercontent.com/18030170/122415105-01dbf580-cf5e-11eb-893b-2de6c07c76d8.png)

2021-06-17 17:43 UTC, kroce commented
Para tener en cuenta: al hacer pruebas con emuladores no me funciona la geolocalización. Con lo cual la parte de dación de turnos hay que probarla directamente desde un dispositivo.

2021-06-18 16:13 UTC, andrrrl commented
> Test en el emulador (Android 7.1): Algunas pantallas todavia tienen problemas en la visualización.
> 
> * Farmacias
> * Tu mapa de salud
> * Mi historial de turnos
> * Datos personales
>   ![historial](https://user-images.githubusercontent.com/18030170/122415105-01dbf580-cf5e-11eb-893b-2de6c07c76d8.png)

Listo eso!

2021-06-23 13:03 UTC, kroce approved these changes

2021-06-25 16:03 UTC, palita1991 approved these changes

2021-06-25 16:04 UTC, merged