feat(MOBILE): scan para registro de familiar
andes/mobile-app pull request #168
Opened 2021-07-27 15:04 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/AM-161

### Funcionalidad desarrollada 

1. En registro de familiar se agrega la funcionalidad del scan

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-08-09 14:25 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4834](http://condorpiedra.andes.gob.ar:85/4834/mochawesome.html)
CYPRESS RUN: [3827](https://dashboard.cypress.io/projects/xr7gft/runs/3827/specs)
TEST START: 2021-08-09T14:25:21.166Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-08-09 15:13 UTC, kroce requested changes
@palita1991 funciona correctamente. Yo haría un cambio en el método scanner() para no repetir código. Lo sacaría como un servicio.

2021-08-09 18:29 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4836](http://condorpiedra.andes.gob.ar:85/4836/mochawesome.html)
CYPRESS RUN: [3829](https://dashboard.cypress.io/projects/xr7gft/runs/3829/specs)
TEST START: 2021-08-09T18:28:29.825Z
TOTAL: 308
SUCCESS: 297
FAIL: 10
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-08-10 13:53 UTC, palita1991 commented
> @palita1991 funciona correctamente. Yo haría un cambio en el método scanner() para no repetir código. Lo sacaría como un servicio.

Corregido

2021-08-10 17:20 UTC, kroce requested changes

2021-08-10 17:20 UTC, kroce commented on src/app/pages/login/informacion-validacion/informacion-validacion.ts
> +        this.barcodeScanner.scan(configScan.setScan()).then((barcodeData) => {
```suggestion
        const options = configScan.setScan();
        this.barcodeScanner.scan(options).then((barcodeData) => {
```

2021-08-10 17:21 UTC, kroce commented on src/providers/config-scan.ts
> +export function setScan() {
A este método le pondría setOptions()

2021-08-10 17:41 UTC, palita1991 commented on src/app/pages/login/informacion-validacion/informacion-validacion.ts
> +        this.barcodeScanner.scan(configScan.setScan()).then((barcodeData) => {
:+1: Corregido @kroce

2021-08-10 17:41 UTC, palita1991 commented on src/providers/config-scan.ts
> +export function setScan() {
:+1: Corregido @kroce

2021-08-10 18:35 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4846](http://condorpiedra.andes.gob.ar:85/4846/mochawesome.html)
CYPRESS RUN: [3839](https://dashboard.cypress.io/projects/xr7gft/runs/3839/specs)
TEST START: 2021-08-10T18:25:58.521Z
TOTAL: 350
SUCCESS: 343
FAIL: 6
SKIPPED: 1

2021-08-10 18:49 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4847](http://condorpiedra.andes.gob.ar:85/4847/mochawesome.html)
CYPRESS RUN: [3840](https://dashboard.cypress.io/projects/xr7gft/runs/3840/specs)
TEST START: 2021-08-10T18:49:05.837Z
TOTAL: 301
SUCCESS: 276
FAIL: 24
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-08-11 11:58 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4850](http://condorpiedra.andes.gob.ar:85/4850/mochawesome.html)
CYPRESS RUN: [3843](https://dashboard.cypress.io/projects/xr7gft/runs/3843/specs)
TEST START: 2021-08-11T11:58:21.941Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-11 12:07 UTC, kroce approved these changes

2021-08-13 16:00 UTC, andrrrl requested changes
Palita! te pido un cambio en el texto para que quede un poco más claro. Cualquier cosa chiflame!

2021-08-13 16:57 UTC, palita1991 commented on src/app/pages/mis-familiares/registro-familiar.html
> +                celular.
Corregido @andrrrl

2021-08-24 18:59 UTC, andrrrl approved these changes

2021-08-24 19:03 UTC, merged