feat(MOBILE):Detalle de vacunación
andes/mobile-app pull request #171
Opened 2021-08-09 15:19 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/AM-174

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-08-09 18:29 UTC, kroce requested changes
Todo bien la funcionalidad, solo un detalle en el icono que se corta.
![Screenshot_20210809-152824_Andes Neuqun](https://user-images.githubusercontent.com/18030170/128755777-c3aae663-37a0-4bf9-990e-84134402d652.jpg)

2021-08-10 16:36 UTC, kroce approved these changes

2021-08-10 16:43 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4842](http://condorpiedra.andes.gob.ar:85/4842/mochawesome.html)
CYPRESS RUN: [3835](https://dashboard.cypress.io/projects/xr7gft/runs/3835/specs)
TEST START: 2021-08-10T16:43:33.606Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-10 17:09 UTC, andrrrl approved these changes
💯 grande paliyo!

2021-08-10 17:29 UTC, merged