feat(CIT):Consultorio Virtual
andes/mobile-app pull request #176
Opened 2021-08-30 11:43 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-113
### Funcionalidad desarrollada 

1. en turno detalle se agrega botón para acceder al turno virtual si es de ese tipo.
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [] No

2021-09-01 13:59 UTC, liquid36 approved these changes

2021-09-01 19:06 UTC, andrrrl reviewed
Walter! probando la funcionalidad encontré que cuando saco el turno por la app móvil misma, no le estamos informando al paciente que el turno que está sacando es virtual.
La seguimos aparte luego.

2021-09-03 17:43 UTC, andrrrl requested changes
Walterito! habría que ver esas cositas, podés **referirte al mockup**, pero sería:
- Quitar mapa (es confuso)
- Mostrar el botón deshabilitado
![image](https://user-images.githubusercontent.com/11394455/132046116-30dc708c-5882-4c8a-b332-932e8b506548.png)

2021-09-06 13:51 UTC, andrrrl requested changes
Haría este pequeño cambio también! para resaltar que es por video llamada.

2021-09-06 13:51 UTC, andrrrl commented on src/components/turno-item/turno-item.html
> +                    Consultorio Virtual
```suggestion
                    <b>Consultorio Virtual por video llamada</b>
```

2021-09-06 14:19 UTC, andrrrl requested changes

2021-09-06 14:19 UTC, andrrrl commented on src/components/turno-item/turno-item.html
> +        <div>
Además creo que está mostrando este mensaje siempre, sea agenda por videollamada o no, puede ser? no veo un control.
Quizá si es virtual muestra ese mensaje, y si es agenda normal muestra el efector.

2021-09-07 12:48 UTC, waltergarrido commented on src/components/turno-item/turno-item.html
> +                    Consultorio Virtual
@andrrrl  corregido.

2021-09-07 12:49 UTC, waltergarrido commented on src/components/turno-item/turno-item.html
> +        <div>
corregido.

2021-09-07 15:09 UTC, andrrrl approved these changes

2021-09-07 15:11 UTC, andrrrl approved these changes
Una beshesa!

2021-09-13 14:23 UTC, merged