HUDS: incorpora pagina de accesos de mi huds
andes/mobile-app pull request #96
Opened 2020-03-18 16:04 UTC by plammel

### Requerimiento
https://proyectos.andes.gob.ar/browse/PRIV-2
 

**IMPORTANTE!** Para implementar este PR es necesario actualizar la versión de angular.
### Funcionalidad desarrollada 

1. Se actualizó la pagina de mi HUDS para incluir acceso a listado de accesos
2. Se creó la página de listado de accesos a mi HUDS:  Esta página implementa ion-infiniteScroll para scroll infinito de appMobile. **IMPORTANTE!** Para implementar este componente es necesario actualizar la versión de angular. 
3. Se creó la página de detalle de acceso a mi HUDS
4. Se incluyó en provider de Paciente, servicio para hacer request a ruta de MobileApp de get de accesosHuds.

### UserStory llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/PRIV-2
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/931
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2020-04-04 02:44 UTC, sychus commented on src/pages/historia-salud/accesos-mi-huds/accesos-mi-huds.html
> +                    No hay registros de historia clínica.
Yo pondría: No existen registros de acceso a su información de salud

2020-08-20 17:09 UTC, sychus commented on src/pages/historia-salud/accesos-mi-huds/accesos-mi-huds.html
> +                    No hay registros de historia clínica.
@plammel verificar el detalle que puse en la api con respecto al authentication. Sólo un detallecito

2020-09-02 18:23 UTC, plammel commented
@andes/ui-ux validar posición de botón y proponer un ícono

2020-09-09 15:23 UTC, JSantarelli reviewed
Quedaron los cambios pusheados.

2020-09-09 16:00 UTC, JSantarelli approved these changes

2020-09-13 15:50 UTC, JSantarelli approved these changes

2021-02-09 12:07 UTC, andrrrl requested changes

2021-02-09 12:07 UTC, andrrrl commented on src/pages/historia-salud/accesos-mi-huds/accesos-mi-huds.html
> +                            <span class="info-profesional" >{{acceso.usuario.nombreCompleto}} <ng-container *ngIf='acceso.usuario.formacionGrado?.length'> | {{ acceso.usuario.matricula }} </ng-contai
Creo que el linteo va a tirar "línea muy larga" acá

2021-02-09 12:09 UTC, andrrrl commented
Más allá de los comentarios del header que son más para tener en cuenta cambios en Ionic 5, casi todo debería resolverse rebaseando.

2021-02-10 11:57 UTC, closed without merging